version: '3.8'

services:
  mysql-order:
    image: mysql:8.3.0
    container_name: mysql-order
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: order
      MYSQL_USER: orderuser
      MYSQL_PASSWORD: orderpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-order-data:/var/lib/mysql

  postgres-student:
    image: postgres:15-alpine
    container_name: postgres-student
    environment:
      POSTGRES_DB: student
      POSTGRES_USER: studentuser
      POSTGRES_PASSWORD: studentpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-student-data:/var/lib/postgresql/data

  postgres-product:
    image: postgres:15-alpine
    container_name: postgres-product
    environment:
      POSTGRES_DB: product
      POSTGRES_USER: productuser
      POSTGRES_PASSWORD: productpassword
    ports:
      - "5433:5432"
    volumes:
      - postgres-product-data:/var/lib/postgresql/data
  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:8.3.0
    volumes:
      - mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: keycloak-mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    volumes:
      - keycloak_import_data:/opt/keycloak/data/
    depends_on:
      - keycloak-mysql

volumes:
  mysql-order-data:
  postgres-student-data:
  postgres-product-data:
  mysql_keycloak_data:
  keycloak_import_data:
